package gov.nih.nci.cagrid.labviewer.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface LabLoaderConstantsBase {
	public static final String SERVICE_NS = "http://labviewer.cagrid.nci.nih.gov/LabLoader";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "LabLoaderKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "LabLoaderResourceProperties");
	public static final QName SERVICEMETADATA = new QName("gme://caGrid.caBIG/1.0/gov.nih.nci.cagrid.metadata", "ServiceMetadata");
	
}
