package gov.nih.nci.cagrid.labviewer.grid.service;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public class StudyLookupServiceImpl extends StudyLookupServiceImplBase {

	
	public StudyLookupServiceImpl() throws RemoteException
	{
		super();
	}
	
  public gov.nih.nci.cabig.ccts.domain.Study getStudy(gov.nih.nci.cabig.ccts.domain.Registration registration)
  	throws RemoteException
  {
    //TODO: Implement this autogenerated method
    throw new RemoteException("Not yet implemented");
  }

}

