<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://caXchange.nci.nih.gov/metadata" xmlns:ns0="http://caXchange.nci.nih.gov/messaging" targetNamespace="http://caXchange.nci.nih.gov/metadata">
	<types>
		<xs:schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://caXchange.nci.nih.gov/metadata" elementFormDefault="qualified" attributeFormDefault="unqualified">
			<import namespace="http://caXchange.nci.nih.gov/messaging" schemaLocation="caXchange.xsd"/>
		<element name="GetCaXchangeMetadataRequest">
			<complexType>
				<sequence/>
			</complexType>
		</element>
		<element name="GetCaXchangeMetadataResponse">
			<complexType>
				<sequence>
					<element ref="ns0:caXchangeRoutingMetadata" minOccurs="1" maxOccurs="1"/>
				</sequence>
			</complexType>
		</element>
	</xs:schema>
	</types>
	<message name="GetCaXchangeMetadataRequest">
		<part name="parameters" element="tns:GetCaXchangeMetadataRequest"/>
	</message>
	<message name="GetCaXchangeMetadataResponse">
		<part name="parameters" element="tns:GetCaXchangeMetadataResponse"/>
	</message>
	<portType name="CaXchangeMetadataPortType">
		<operation name="getCaXchangeMetadata">
			<input message="tns:GetCaXchangeMetadataRequest" wsa:Action="http://caxchange.nci.nih.gov/metadata/GetCaXchangeMetadataRequest"/>
			<output message="tns:GetCaXchangeMetadataResponse" wsa:Action="http://caxchange.nci.nih.gov/metadata/GetCaXchangeMetadataResponse"/>
		</operation>
	</portType>
</definitions>
