package gov.nih.nci.cagrid.caxchange.context.service;

import gov.nih.nci.cagrid.caxchange.context.service.globus.resource.CaXchangeResponseServiceResource;
import gov.nih.nci.caxchange.ResponseMessage;

import java.rmi.RemoteException;

/** 
 * TODO:I am the service side implementation class.  IMPLEMENT AND DOCUMENT ME
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public class CaXchangeResponseServiceImpl extends CaXchangeResponseServiceImplBase {

	
	public CaXchangeResponseServiceImpl() throws RemoteException {
		super();
	}
	

  public gov.nih.nci.caxchange.ResponseMessage getResponse() throws RemoteException {
      try {
          gov.nih.nci.cagrid.caxchange.context.service.globus.resource.BaseResourceHome brh =getResourceHome();
          CaXchangeResponseServiceResource currentResource = brh.getAddressedResource();
          ResponseMessage responseMessage = currentResource.getCaXchangeResponseMessageValue();
          return responseMessage;
      }
      catch (Exception e) {
         //TODO: Implement this autogenerated method
         e.printStackTrace();
          throw new RemoteException("Error getting response status ", e);
      }
  }

}

