package gov.nih.nci.ccts.grid.studyconsumer.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.4
 */
public interface StudyConsumerConstantsBase {
	public static final String SERVICE_NS = "http://studyconsumer.grid.ccts.nci.nih.gov/StudyConsumer";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "StudyConsumerKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "StudyConsumerResourceProperties");
	
}
