<?xml version="1.0" encoding="UTF-8"?>

<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/03/addressing"
	xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/"
	xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/"
	xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:tns="http://caXchange.nci.nih.gov/synchronousrequest"
	xmlns:ns0="http://caXchange.nci.nih.gov/messaging" targetNamespace="http://caXchange.nci.nih.gov/synchronousrequest">

	<types>
		<xs:schema xmlns="http://www.w3.org/2001/XMLSchema"
			targetNamespace="http://caXchange.nci.nih.gov/synchronousrequest"
			elementFormDefault="qualified" attributeFormDefault="unqualified">
			<import namespace="http://caXchange.nci.nih.gov/messaging"
				schemaLocation="caXchange.xsd" />
		</xs:schema>
	</types>	

	<message name="ProcessRequestSynchronouslyRequest">
		<part name="parameters" element="ns0:caXchangeRequestMessage"/>
	</message>
	<message name="ProcessRequestSynchronouslyResponse">
		<part name="parameters" element="ns0:caXchangeResponseMessage" />
	</message>


	<portType name="CaXchangeRequestProcessorPortType">		
		<operation name="processRequestSynchronously">
			<input message="tns:ProcessRequestSynchronouslyRequest"
				wsa:Action="http://caxchange.cagrid.nci.nih.gov/CaXchangeRequestProcessor/ProcessRequestSynchronouslyRequest" />
			<output message="tns:ProcessRequestSynchronouslyResponse" 
				wsa:Action="http://caxchange.cagrid.nci.nih.gov/CaXchangeRequestProcessor/ProcessRequestSynchronouslyResponse"/>
		</operation>
	</portType>

</definitions>
	