/*
 * Copyright ScenPro, Inc and SemanticBits, LLC
 * 
 * Distributed under the OSI-approved BSD 3-Clause License.
 * See http://ncip.github.com/labviewer/LICENSE.txt for details.
 */
package gov.nih.nci.cagrid.labviewer.grid.common;

import javax.xml.namespace.QName;


/**
 * This class is autogenerated, DO NOT EDIT
 *
 * @created by Introduce Toolkit version 1.3
 */
public interface StudyServiceConstantsBase {
	public static final String SERVICE_NS = "http://grid.labviewer.cagrid.nci.nih.gov/StudyService";
	public static final QName RESOURCE_KEY = new QName(SERVICE_NS, "StudyServiceKey");
	public static final QName RESOURCE_PROPERTY_SET = new QName(SERVICE_NS, "StudyServiceResourceProperties");
	
}
