CREATE USER caxchange IDENTIFIED BY caxchange DEFAULT TABLESPACE USERS;
GRANT CREATE SESSION TO caxchange;
GRANT CREATE TABLE TO caxchange;
GRANT CREATE VIEW TO caxchange;
GRANT CREATE SEQUENCE TO caxchange; 
GRANT CREATE SYNONYM TO caxchange;
ALTER USER caxchange QUOTA unlimited ON USERS;
exit


