package gov.nih.nci.ccts.grid.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface RegistrationConsumer {

  /**
   * Rollback (delete) the Registration
   *
   * @param registration
   * @throws InvalidRegistrationException
   *	
   */
  public void rollback(gov.nih.nci.ccts.grid.Registration registration) throws RemoteException, gov.nih.nci.ccts.grid.stubs.types.InvalidRegistrationException ;

  /**
   * commit the Registration
   *
   * @param registration
   * @throws InvalidRegistrationException
   *	
   */
  public void commit(gov.nih.nci.ccts.grid.Registration registration) throws RemoteException, gov.nih.nci.ccts.grid.stubs.types.InvalidRegistrationException ;

  /**
   * Register a Patient to a Study
   *
   * @param registration
   * @throws InvalidRegistrationException
   *	
   * @throws RegistrationConsumptionException
   *	
   */
  public gov.nih.nci.ccts.grid.Registration register(gov.nih.nci.ccts.grid.Registration registration) throws RemoteException, gov.nih.nci.ccts.grid.stubs.types.InvalidRegistrationException, gov.nih.nci.ccts.grid.stubs.types.RegistrationConsumptionException ;

}

