package gov.nih.nci.cagrid.caxchange.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface CaXchangeRequestProcessorI {

  /**
   * Process an incoming request asynchronously.
   *
   * @param caXchangeRequestMessage
   * @throws CaXchangeFault
   *	
   */
  public gov.nih.nci.cagrid.caxchange.context.stubs.types.CaXchangeResponseServiceReference processRequestAsynchronously(gov.nih.nci.caxchange.Message caXchangeRequestMessage) throws RemoteException, gov.nih.nci.cagrid.caxchange.stubs.types.CaXchangeFault ;

  /**
   * Process a request for caXchange synchronously.
   *
   * @param caXchangeRequestMessage
   * @throws CaXchangeFault
   *	
   */
  public gov.nih.nci.caxchange.ResponseMessage processRequestSynchronously(gov.nih.nci.caxchange.Message caXchangeRequestMessage) throws RemoteException, gov.nih.nci.cagrid.caxchange.stubs.types.CaXchangeFault ;

}

