package gov.nih.nci.cagrid.coppa.person.service.service.globus;

import gov.nih.nci.cagrid.coppa.person.service.service.CoppaPersonServiceImpl;

import java.rmi.RemoteException;

/** 
 * DO NOT EDIT:  This class is autogenerated!
 *
 * This class implements each method in the portType of the service.  Each method call represented
 * in the port type will be then mapped into the unwrapped implementation which the user provides
 * in the CoppaPersonServiceImpl class.  This class handles the boxing and unboxing of each method call
 * so that it can be correclty mapped in the unboxed interface that the developer has designed and 
 * has implemented.  Authorization callbacks are automatically made for each method based
 * on each methods authorization requirements.
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public class CoppaPersonServiceProviderImpl{
	
	CoppaPersonServiceImpl impl;
	
	public CoppaPersonServiceProviderImpl() throws RemoteException {
		impl = new CoppaPersonServiceImpl();
	}
	

    public gov.nih.nci.cagrid.coppa.person.service.stubs.SearchResponse search(gov.nih.nci.cagrid.coppa.person.service.stubs.SearchRequest params) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault {
    gov.nih.nci.cagrid.coppa.person.service.stubs.SearchResponse boxedResult = new gov.nih.nci.cagrid.coppa.person.service.stubs.SearchResponse();
    boxedResult.setPerson(impl.search(params.getPerson().getPerson()));
    return boxedResult;
  }

    public gov.nih.nci.cagrid.coppa.person.service.stubs.GetPersonResponse getPerson(gov.nih.nci.cagrid.coppa.person.service.stubs.GetPersonRequest params) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault, gov.nih.nci.cagrid.coppa.person.service.stubs.types.NullifiedEntityFault {
    gov.nih.nci.cagrid.coppa.person.service.stubs.GetPersonResponse boxedResult = new gov.nih.nci.cagrid.coppa.person.service.stubs.GetPersonResponse();
    boxedResult.setPerson(impl.getPerson(params.getIi().getIi()));
    return boxedResult;
  }

    public gov.nih.nci.cagrid.coppa.person.service.stubs.CreatePersonResponse createPerson(gov.nih.nci.cagrid.coppa.person.service.stubs.CreatePersonRequest params) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault, gov.nih.nci.cagrid.coppa.person.service.stubs.types.EntityValidationFault {
    gov.nih.nci.cagrid.coppa.person.service.stubs.CreatePersonResponse boxedResult = new gov.nih.nci.cagrid.coppa.person.service.stubs.CreatePersonResponse();
    boxedResult.setIi(impl.createPerson(params.getPerson().getPerson()));
    return boxedResult;
  }

    public gov.nih.nci.cagrid.coppa.person.service.stubs.UpdatePersonResponse updatePerson(gov.nih.nci.cagrid.coppa.person.service.stubs.UpdatePersonRequest params) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault, gov.nih.nci.cagrid.coppa.person.service.stubs.types.EntityValidationFault {
    gov.nih.nci.cagrid.coppa.person.service.stubs.UpdatePersonResponse boxedResult = new gov.nih.nci.cagrid.coppa.person.service.stubs.UpdatePersonResponse();
    impl.updatePerson(params.getPerson().getPerson());
    return boxedResult;
  }

    public gov.nih.nci.cagrid.coppa.person.service.stubs.UpdatePersonStatusResponse updatePersonStatus(gov.nih.nci.cagrid.coppa.person.service.stubs.UpdatePersonStatusRequest params) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.EntityValidationFault {
    gov.nih.nci.cagrid.coppa.person.service.stubs.UpdatePersonStatusResponse boxedResult = new gov.nih.nci.cagrid.coppa.person.service.stubs.UpdatePersonStatusResponse();
    impl.updatePersonStatus(params.getIi().getIi(),params.getCd().getCd());
    return boxedResult;
  }

    public gov.nih.nci.cagrid.coppa.person.service.stubs.ValidateResponse validate(gov.nih.nci.cagrid.coppa.person.service.stubs.ValidateRequest params) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault {
    gov.nih.nci.cagrid.coppa.person.service.stubs.ValidateResponse boxedResult = new gov.nih.nci.cagrid.coppa.person.service.stubs.ValidateResponse();
    boxedResult.setMap(impl.validate(params.getPerson().getPerson()));
    return boxedResult;
  }

}
