package gov.nih.nci.caxchange.caxchangerequest;

import java.util.concurrent.Future;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.ws.rs.POST;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.Response;

/**
 * This class was generated by Apache CXF 2.2
 * Mon Apr 20 15:03:48 EDT 2009
 * Generated source version: 2.2
 * 
 */
 
@WebService(targetNamespace = "http://caXchange.nci.nih.gov/caxchangerequest", name = "CaXchangeRequestPortType")
@XmlSeeAlso({gov.nih.nci.caxchange.messaging.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CaXchangeRequestPortType {

    @WebMethod(operationName = "ProcessRequest")
    public Response<gov.nih.nci.caxchange.messaging.ResponseMessage> processRequestAsync(
        @WebParam(partName = "parameters", name = "caXchangeRequestMessage", targetNamespace = "http://caXchange.nci.nih.gov/messaging")
        gov.nih.nci.caxchange.messaging.Message parameters
    );

    @WebMethod(operationName = "ProcessRequest")
    public Future<?> processRequestAsync(
        @WebParam(partName = "parameters", name = "caXchangeRequestMessage", targetNamespace = "http://caXchange.nci.nih.gov/messaging")
        gov.nih.nci.caxchange.messaging.Message parameters,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<gov.nih.nci.caxchange.messaging.ResponseMessage> asyncHandler
    );

    @WebResult(name = "caXchangeResponseMessage", targetNamespace = "http://caXchange.nci.nih.gov/messaging", partName = "parameters")
    @WebMethod(operationName = "ProcessRequest")
    @POST
    public gov.nih.nci.caxchange.messaging.ResponseMessage processRequest(
        @WebParam(partName = "parameters", name = "caXchangeRequestMessage", targetNamespace = "http://caXchange.nci.nih.gov/messaging")
        gov.nih.nci.caxchange.messaging.Message parameters
    );
}
