
/*
 * 
 */

package gov.nih.nci.caxchange.caxchangerequest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2
 * Mon Apr 20 15:03:48 EDT 2009
 * Generated source version: 2.2
 * 
 */


@WebServiceClient(name = "CaXchangeRequestService", 
                  wsdlLocation = "http://localhost:8193/CaXchangeRequestService?wsdl",
                  targetNamespace = "http://caXchange.nci.nih.gov/caxchangerequest") 
public class CaXchangeRequestService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://caXchange.nci.nih.gov/caxchangerequest", "CaXchangeRequestService");
    public final static QName Soap = new QName("http://caXchange.nci.nih.gov/caxchangerequest", "soap");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8193/CaXchangeRequestService?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8193/CaXchangeRequestService?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public CaXchangeRequestService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CaXchangeRequestService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CaXchangeRequestService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns CaXchangeRequestPortType
     */
    @WebEndpoint(name = "soap")
    public CaXchangeRequestPortType getSoap() {
        return super.getPort(Soap, CaXchangeRequestPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CaXchangeRequestPortType
     */
    @WebEndpoint(name = "soap")
    public CaXchangeRequestPortType getSoap(WebServiceFeature... features) {
        return super.getPort(Soap, CaXchangeRequestPortType.class, features);
    }

}
