/* *****************************************************************************
********************************************************************************

SCRIPT NAME:  DDL_For_CTOM_Sequences.sql 
PURPOSE:      Create or recreate sequences for CTOM tables. 
AUTHOR:		  ScenPro, Inc.
DATE:		  March, 2006 
VERSION: 	  CTOM v0.5.3 
NOTE:		  This script was created in Toad and is best viewed through that tool.
UPDATE LOG: 
Date        Description 
----------  --------------------------------------------------------------------
2007-05-15  Dropped adverse_event_report_seq 
2007-05-17  Dropped sequences for all subclass tables, pat_hash_seq, and 
			patient_hash_seq too 
2007-05-21  Removed the drop/create for sift_and_merge_log_seq 
2007-08-07  Removed INVESTIGATOR_SEQ AND PARTICIPANT_SEQ as sequences, created
            PERSON_SEQ as a sequence and created synonyms to it called INVESTIGATOR_SEQ
            and PARTICIPANT_SEQ
2007-08-27  Added sequence for healthcare_site_investigator
2007-10-05  Dropped healthcare_site_seq and replaced it with organizaton_seq and 
            synonyms for healthcare site, performing and central laboratories
            pointing to it to support both original and new caXchange organizations
2007-10-16  Added LAB_VIEWER_STATUS_SEQ
2007-10-17  Added IDENTIFIER_SEQ

********************************************************************************
***************************************************************************** */

--SET ECHO ON

--SPOOL DDL_For_CTOM_Sequences.lst


DROP SEQUENCE IF EXISTS ACTIVITY_RELATIONSHIP_SEQ;
DROP SEQUENCE IF EXISTS ACTIVITY_SEQ;
DROP SEQUENCE IF EXISTS ADVERSE_EVENT_THERAPY_SEQ;
DROP SEQUENCE IF EXISTS AGENT_OCCURRENCE_SEQ;
DROP SEQUENCE IF EXISTS AGENT_SEQ;
DROP SEQUENCE IF EXISTS ASSESSMENT_RELATIONSHIP_SEQ;
DROP SEQUENCE IF EXISTS ASSESSMENT_SEQ;
DROP SEQUENCE IF EXISTS CANCER_STAGE_SEQ;
DROP SEQUENCE IF EXISTS CONCEPT_DESCRIPTOR_SEQ;
DROP SEQUENCE IF EXISTS ELIGIBILITY_CHECKLIST_SEQ;
DROP SEQUENCE IF EXISTS ELIGIBILITY_CHECKLST_CRITR_SEQ;
DROP SEQUENCE IF EXISTS ELIGIBILITY_CRITERIA_SEQ;
DROP SEQUENCE IF EXISTS FEMALE_REPRDCTVE_CHRCTRSTC_SEQ;
DROP SEQUENCE IF EXISTS HEALTHCARE_SITE_INVESTIGTR_SEQ;
DROP SEQUENCE IF EXISTS HEALTHCARE_SITE_PRTCPNT_SEQ;
DROP SEQUENCE IF EXISTS HEALTHCARE_SIT_PRTCPNT_ROL_SEQ;
DROP SEQUENCE IF EXISTS HISTOPATHOLOGY_GRADE_SEQ;
DROP SEQUENCE IF EXISTS IDENTIFIER_SEQ;
DROP SEQUENCE IF EXISTS LAB_VIEWER_STATUS_SEQ;
DROP SEQUENCE IF EXISTS METASTASIS_SITE_SEQ;
DROP SEQUENCE IF EXISTS NEOPLASM_SEQ;
DROP SEQUENCE IF EXISTS OBSERVATION_ASSESSMENT_SEQ;
DROP SEQUENCE IF EXISTS OBSERVATION_RELATIONSHIP_SEQ;
DROP SEQUENCE IF EXISTS OBSERVATION_SEQ;
DROP SEQUENCE IF EXISTS ORGANIZATION_SEQ;
DROP SEQUENCE IF EXISTS PARTICIPANT_ELIGBLTY_ANSWR_SEQ;
DROP SEQUENCE IF EXISTS PERSON_OCCUPATION_SEQ;
DROP SEQUENCE IF EXISTS PERSON_SEQ;
DROP SEQUENCE IF EXISTS PROTOCOL_SEQ;
DROP SEQUENCE IF EXISTS PROTOCOL_PARTICPNT_ELGBLTY_SEQ;
DROP SEQUENCE IF EXISTS PROTOCOL_STATUS_SEQ;
DROP SEQUENCE IF EXISTS SPECIMEN_SEQ;
DROP SEQUENCE IF EXISTS STUDY_AGENT_SEQ;
DROP SEQUENCE IF EXISTS STUDY_INVESTIGATOR_SEQ;
DROP SEQUENCE IF EXISTS STUDY_PARTICIPANT_ASSGNMNT_SEQ;
DROP SEQUENCE IF EXISTS STUDY_SITE_SEQ;
DROP SEQUENCE IF EXISTS STUDY_TIME_POINT_SEQ;


CREATE SEQUENCE ACTIVITY_RELATIONSHIP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ACTIVITY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ADVERSE_EVENT_THERAPY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AGENT_OCCURRENCE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AGENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ASSESSMENT_RELATIONSHIP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ASSESSMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CANCER_STAGE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CONCEPT_DESCRIPTOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ELIGIBILITY_CHECKLIST_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ELIGIBILITY_CHECKLST_CRITR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ELIGIBILITY_CRITERIA_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FEMALE_REPRDCTVE_CHRCTRSTC_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HEALTHCARE_SITE_INVESTIGTR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HEALTHCARE_SITE_PRTCPNT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HEALTHCARE_SIT_PRTCPNT_ROL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE HISTOPATHOLOGY_GRADE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IDENTIFIER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE LAB_VIEWER_STATUS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE METASTASIS_SITE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE NEOPLASM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OBSERVATION_ASSESSMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OBSERVATION_RELATIONSHIP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE OBSERVATION_SEQ START WITH 1 INCREMENT BY 1;
-- organization_seq is used for healthcare sites, performing and central laboratories so that the organization_view can eventually have a single unique series of numbers for the id column
CREATE SEQUENCE ORGANIZATION_SEQ START WITH 1 INCREMENT BY 1;
--CREATE SYNONYM SEQUENCE HEALTHCARE_SITE_SEQ ON ORGANIZATION_SEQ;
--CREATE SYNONYM SEQUENCE CENTRAL_LABORATORY_SEQ ON ORGANIZATION_SEQ;
--CREATE SYNONYM SEQUENCE PERFORMING_LABORATORY_SEQ ON ORGANIZATION_SEQ;

CREATE SEQUENCE PARTICIPANT_ELIGBLTY_ANSWR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PERSON_OCCUPATION_SEQ START WITH 1 INCREMENT BY 1;
-- person_seq is used for both investigators and participants so that the person_view can have a single unique series of numbers for the id column 
CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1;
--CREATE SYNONYM SEQUENCE INVESTIGATOR_SEQ ON PERSON_SEQ;
--CREATE SYNONYM SEQUENCE PARTICIPANT_SEQ ON PERSON_SEQ;
-- 
CREATE SEQUENCE PROTOCOL_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PROTOCOL_PARTICPNT_ELGBLTY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE PROTOCOL_STATUS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SPECIMEN_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STUDY_AGENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STUDY_INVESTIGATOR_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STUDY_PARTICIPANT_ASSGNMNT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STUDY_SITE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE STUDY_TIME_POINT_SEQ START WITH 1 INCREMENT BY 1;


--SPOOL OFF

--SET ECHO OFF
