package gov.nih.nci.cagrid.coppa.person.service.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface CoppaPersonServiceI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * Search persons
   *
   * @param person
   * @throws CoppaPersonServiceFault
   *	
   */
  public gov.nih.nci.cagrid.person.service.Person[] search(gov.nih.nci.cagrid.person.service.Person person) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault ;

  /**
   * gets the person for the given identifier
   *
   * @param ii
   * @throws CoppaPersonServiceFault
   *	
   * @throws NullifiedEntityFault
   *	
   */
  public gov.nih.nci.cagrid.person.service.Person getPerson(gov.nih.nci.cagrid.coppa.iso.Ii ii) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault, gov.nih.nci.cagrid.coppa.person.service.stubs.types.NullifiedEntityFault ;

  /**
   * Creates a COPPA person object.
   *
   * @param person
   * @throws CoppaPersonServiceFault
   *	
   * @throws EntityValidationFault
   *	
   */
  public gov.nih.nci.cagrid.coppa.iso.Ii createPerson(gov.nih.nci.cagrid.person.service.Person person) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault, gov.nih.nci.cagrid.coppa.person.service.stubs.types.EntityValidationFault ;

  /**
   * Update a person object
   *
   * @param person
   * @throws CoppaPersonServiceFault
   *	
   * @throws EntityValidationFault
   *	
   */
  public void updatePerson(gov.nih.nci.cagrid.person.service.Person person) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault, gov.nih.nci.cagrid.coppa.person.service.stubs.types.EntityValidationFault ;

  /**
   * Update a persons status.
   *
   * @param ii
   * @param cd
   * @throws EntityValidationFault
   *	
   */
  public void updatePersonStatus(gov.nih.nci.cagrid.coppa.iso.Ii ii,gov.nih.nci.cagrid.coppa.iso.Cd cd) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.EntityValidationFault ;

  /**
   * validate a person
   *
   * @param person
   * @throws CoppaPersonServiceFault
   *	
   */
  public gov.nih.nci.cagrid.coppa.iso.Map validate(gov.nih.nci.cagrid.person.service.Person person) throws RemoteException, gov.nih.nci.cagrid.coppa.person.service.stubs.types.CoppaPersonServiceFault ;

}

