# Replace the <<database_name>> with proper database name that is to be created. 

USE @CAXCHANGE_DATABASE@;
commit;
CREATE TABLE  IF NOT EXISTS CAXCHANGE_MESSAGES
(
   MESSAGE_ID  VARCHAR(500) NOT NULL,
   ORIGINAL_MESSAGE  MEDIUMTEXT,
   CONSTRAINT PRIMARY KEY (MESSAGE_ID(500))
);

