DROP TABLE IF EXISTS CSM_APPLICATION CASCADE;

DROP TABLE IF EXISTS  CSM_GROUP CASCADE;

DROP TABLE IF EXISTS  CSM_PG_PE CASCADE;

DROP TABLE IF EXISTS  CSM_PRIVILEGE CASCADE;

DROP TABLE IF EXISTS  CSM_PROTECTION_ELEMENT CASCADE;

DROP TABLE IF EXISTS  CSM_PROTECTION_GROUP CASCADE;

DROP TABLE IF EXISTS  CSM_ROLE CASCADE;

DROP TABLE IF EXISTS  CSM_ROLE_PRIVILEGE CASCADE;

DROP TABLE IF EXISTS CSM_USER CASCADE;

DROP TABLE IF EXISTS  CSM_USER_GROUP CASCADE;

DROP TABLE IF EXISTS  CSM_USER_GROUP_ROLE_PG CASCADE;

DROP TABLE IF EXISTS  CSM_USER_PE CASCADE;

DROP TABLE IF EXISTS  DEATH_SUMMARY CASCADE;

DROP TABLE IF EXISTS  DIAGNOSIS CASCADE;

DROP TABLE IF EXISTS DISEASE_RESPONSE CASCADE;

DROP TABLE IF EXISTS ELIGIBILITY_CHECKLIST CASCADE;

DROP TABLE IF EXISTS ELIGIBILITY_CHECKLIST_CRITERIA CASCADE;

DROP TABLE IF EXISTS ELIGIBILITY_CRITERIA CASCADE;

DROP TABLE IF EXISTS FEMALE_REPRODUCTVE_CHARACTRSTC CASCADE;

DROP TABLE IF EXISTS HEALTHCARE_SITE CASCADE;

DROP TABLE IF EXISTS HEALTHCARE_SITE_INVESTIGATOR CASCADE;

DROP TABLE IF EXISTS HEALTHCARE_SITE_PRTCPNT CASCADE;

DROP TABLE IF EXISTS HEALTHCARE_SITE_PRTCPNT_ROLE CASCADE;

DROP TABLE IF EXISTS HISTOPATHOLOGY CASCADE;

DROP TABLE IF EXISTS HISTOPATHOLOGY_GRADE CASCADE;

DROP TABLE IF EXISTS IDENTIFIER CASCADE;

DROP TABLE IF EXISTS IMAGING CASCADE;

DROP TABLE IF EXISTS INVESTIGATOR CASCADE;

DROP TABLE IF EXISTS LAB_VIEWER_STATUS CASCADE;

DROP TABLE IF EXISTS LESION_DESCRIPTION CASCADE;

DROP TABLE IF EXISTS LESION_EVALUATION CASCADE;

DROP TABLE IF EXISTS METASTASIS_SITE CASCADE;

DROP TABLE IF EXISTS NEOPLASM CASCADE;

DROP TABLE IF EXISTS OBSERVATION CASCADE;

DROP TABLE IF EXISTS OBSERVATION_ASSESSMENT CASCADE;

DROP TABLE IF EXISTS OBSERVATION_RELATIONSHIP CASCADE;

DROP TABLE IF EXISTS PARTICIPANT CASCADE;

DROP TABLE IF EXISTS PARTICIPANT_ELIGIBILITY_ANSWER CASCADE;

DROP TABLE IF EXISTS PERFORMING_LABORATORY CASCADE;

DROP TABLE IF EXISTS PERSON_OCCUPATION CASCADE;

DROP TABLE IF EXISTS PROCEDURE CASCADE;

DROP TABLE IF EXISTS PROTOCOL CASCADE;

DROP TABLE IF EXISTS PROTOCOL_PARTICIPANT_ELIGIBLTY CASCADE;

DROP TABLE IF EXISTS PROTOCOL_STATUS CASCADE;

DROP TABLE IF EXISTS QUALITATIVE_EVALUATION CASCADE;

DROP TABLE IF EXISTS RADIATION CASCADE;

DROP TABLE IF EXISTS SPECIMEN CASCADE;

DROP TABLE IF EXISTS SPECIMEN_COLLECTION CASCADE;

DROP TABLE IF EXISTS STUDY_AGENT CASCADE;

DROP TABLE IF EXISTS STUDY_INVESTIGATOR CASCADE;

DROP TABLE IF EXISTS STUDY_PARTICIPANT_ASSIGNMENT CASCADE;

DROP TABLE IF EXISTS STUDY_SITE CASCADE;

DROP TABLE IF EXISTS STUDY_TIME_POINT CASCADE;

DROP TABLE IF EXISTS SUBSTANCE_ADMINISTRATION CASCADE;

DROP TABLE IF EXISTS SURGERY CASCADE;

DROP TABLE IF EXISTS ACTIVITY CASCADE;

DROP TABLE IF EXISTS ACTIVITY_RELATIONSHIP CASCADE;

DROP TABLE IF EXISTS ADVERSE_EVENT CASCADE;

DROP TABLE IF EXISTS ADVERSE_EVENT_THERAPY CASCADE;

DROP TABLE IF EXISTS AGENT CASCADE;

DROP TABLE IF EXISTS AGENT_OCCURRENCE CASCADE;

DROP TABLE IF EXISTS ASSESSMENT_RELATIONSHIP CASCADE;

DROP TABLE IF EXISTS ASSESSMENT CASCADE;

DROP TABLE IF EXISTS CANCER_STAGE CASCADE;

DROP TABLE IF EXISTS CENTRAL_LABORATORY CASCADE;

DROP TABLE IF EXISTS CLINICAL_RESULT CASCADE;

DROP TABLE IF EXISTS CONCEPT_DESCRIPTOR CASCADE;

DROP TABLE IF EXISTS  CSM_FILTER_CLAUSE CASCADE;

DROP TABLE IF EXISTS CSM_APPLICATION CASCADE;

DROP TABLE IF EXISTS  CSM_GROUP CASCADE;

DROP TABLE IF EXISTS  CSM_PG_PE CASCADE;

DROP TABLE IF EXISTS  CSM_PRIVILEGE CASCADE;

DROP TABLE IF EXISTS  CSM_PROTECTION_ELEMENT CASCADE;

DROP TABLE IF EXISTS  CSM_PROTECTION_GROUP CASCADE;

DROP TABLE IF EXISTS  CSM_ROLE CASCADE;

DROP TABLE IF EXISTS  CSM_ROLE_PRIVILEGE CASCADE;

DROP TABLE IF EXISTS CSM_USER CASCADE;

DROP TABLE IF EXISTS  CSM_USER_GROUP CASCADE;

DROP TABLE IF EXISTS  CSM_USER_GROUP_ROLE_PG CASCADE;

DROP TABLE IF EXISTS  CSM_USER_PE CASCADE;

DROP TABLE IF EXISTS  DEATH_SUMMARY CASCADE;

DROP TABLE IF EXISTS  DIAGNOSIS CASCADE;

DROP TABLE IF EXISTS DISEASE_RESPONSE CASCADE;

DROP TABLE IF EXISTS ELIGIBILITY_CHECKLIST CASCADE;

DROP TABLE IF EXISTS ELIGIBILITY_CHECKLIST_CRITERIA CASCADE;

DROP TABLE IF EXISTS ELIGIBILITY_CRITERIA CASCADE;

DROP TABLE IF EXISTS FEMALE_REPRODUCTVE_CHARACTRSTC CASCADE;

DROP TABLE IF EXISTS HEALTHCARE_SITE CASCADE;

DROP TABLE IF EXISTS HEALTHCARE_SITE_INVESTIGATOR CASCADE;

DROP TABLE IF EXISTS HEALTHCARE_SITE_PRTCPNT CASCADE;

DROP TABLE IF EXISTS HEALTHCARE_SITE_PRTCPNT_ROLE CASCADE;

DROP TABLE IF EXISTS HISTOPATHOLOGY CASCADE;

DROP TABLE IF EXISTS HISTOPATHOLOGY_GRADE CASCADE;

DROP TABLE IF EXISTS IDENTIFIER CASCADE;

DROP TABLE IF EXISTS IMAGING CASCADE;

DROP TABLE IF EXISTS INVESTIGATOR CASCADE;

DROP TABLE IF EXISTS LAB_VIEWER_STATUS CASCADE;

DROP TABLE IF EXISTS LESION_DESCRIPTION CASCADE;

DROP TABLE IF EXISTS LESION_EVALUATION CASCADE;

DROP TABLE IF EXISTS METASTASIS_SITE CASCADE;

DROP TABLE IF EXISTS NEOPLASM CASCADE;

DROP TABLE IF EXISTS OBSERVATION CASCADE;

DROP TABLE IF EXISTS OBSERVATION_ASSESSMENT CASCADE;

DROP TABLE IF EXISTS OBSERVATION_RELATIONSHIP CASCADE;

DROP TABLE IF EXISTS PARTICIPANT CASCADE;

DROP TABLE IF EXISTS PARTICIPANT_ELIGIBILITY_ANSWER CASCADE;

DROP TABLE IF EXISTS PERFORMING_LABORATORY CASCADE;

DROP TABLE IF EXISTS PERSON_OCCUPATION CASCADE;

DROP TABLE IF EXISTS PROCEDURE CASCADE;

DROP TABLE IF EXISTS PROTOCOL CASCADE;

DROP TABLE IF EXISTS PROTOCOL_PARTICIPANT_ELIGIBLTY CASCADE;

DROP TABLE IF EXISTS PROTOCOL_STATUS CASCADE;

DROP TABLE IF EXISTS QUALITATIVE_EVALUATION CASCADE;

DROP TABLE IF EXISTS RADIATION CASCADE;

DROP TABLE IF EXISTS SPECIMEN CASCADE;

DROP TABLE IF EXISTS SPECIMEN_COLLECTION CASCADE;

DROP TABLE IF EXISTS STUDY_AGENT CASCADE;

DROP TABLE IF EXISTS STUDY_INVESTIGATOR CASCADE;

DROP TABLE IF EXISTS STUDY_PARTICIPANT_ASSIGNMENT CASCADE;

DROP TABLE IF EXISTS STUDY_SITE CASCADE;

DROP TABLE IF EXISTS STUDY_TIME_POINT CASCADE;

DROP TABLE IF EXISTS SUBSTANCE_ADMINISTRATION CASCADE;

DROP TABLE IF EXISTS SURGERY CASCADE;

DROP TABLE IF EXISTS ACTIVITY CASCADE;

DROP TABLE IF EXISTS ACTIVITY_RELATIONSHIP CASCADE;

DROP TABLE IF EXISTS ADVERSE_EVENT CASCADE;

DROP TABLE IF EXISTS ADVERSE_EVENT_THERAPY CASCADE;

DROP TABLE IF EXISTS AGENT CASCADE;

DROP TABLE IF EXISTS AGENT_OCCURRENCE CASCADE;

DROP TABLE IF EXISTS ASSESSMENT_RELATIONSHIP CASCADE;

DROP TABLE IF EXISTS ASSESSMENT CASCADE;

DROP TABLE IF EXISTS CANCER_STAGE CASCADE;

DROP TABLE IF EXISTS CENTRAL_LABORATORY CASCADE;

DROP TABLE IF EXISTS CLINICAL_RESULT CASCADE;

DROP TABLE IF EXISTS CONCEPT_DESCRIPTOR CASCADE;

DROP TABLE IF EXISTS  CSM_FILTER_CLAUSE CASCADE;

DROP TABLE IF EXISTS  CASCADE;

DROP TABLE IF EXISTS  DATABASECHANGELOG CASCADE;

DROP TABLE IF EXISTS  DATABASECHANGELOGLOCK CASCADE;

COMMIT;

COMMIT;