DROP TABLE IF EXISTS LV_PROPERTY
;

CREATE TABLE LV_PROPERTY ( 
    ID SERIAL NOT NULL,
    PROPERTY_NAME  varchar(20) NOT NULL,
    PROPERTY_VALUE varchar(5000) NOT NULL,
    PRIMARY KEY (ID)
)
;
