package gov.nih.nci.cagrid.labviewer.grid.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.1
 * 
 */
public interface StudyLookupServiceI {

  public gov.nih.nci.ccts.grid.Study getStudy(gov.nih.nci.ccts.grid.Registration registration) throws RemoteException ;

}

