
DROP TABLE IF EXISTS CSM_FILTER_CLAUSE;

DROP SEQUENCE IF EXISTS CSM_FILTER_CLAUSE_FILTE_ID_SEQ;

CREATE TABLE CSM_FILTER_CLAUSE (
            FILTER_CLAUSE_ID integer NOT NULL,
            CLASS_NAME VARCHAR(100) NOT NULL,
            FILTER_CHAIN VARCHAR(2000) NOT NULL,
            TARGET_CLASS_NAME VARCHAR (100) NOT NULL,
            TARGET_CLASS_ATTRIBUTE_NAME VARCHAR (100) NOT NULL,
            TARGET_CLASS_ATTRIBUTE_TYPE VARCHAR (100) NOT NULL,
            TARGET_CLASS_ALIAS VARCHAR (100),
            TARGET_CLASS_ATTRIBUTE_ALIAS VARCHAR (100),
            GENERATED_SQL VARCHAR (4000) NOT NULL,
            APPLICATION_ID integer NOT NULL,
            UPDATE_DATE timestamp NOT NULL
)
;
 
CREATE SEQUENCE CSM_FILTER_CLAUSE_FILTE_ID_SEQ increment by 1 start with 1 minvalue 1;
 
ALTER TABLE CSM_PROTECTION_ELEMENT ADD column ATTRIBUTE_VALUE VARCHAR(100) ;
 
ALTER TABLE CSM_PROTECTION_ELEMENT DROP CONSTRAINT UQ_PE_OBJ_ATT_APP_ID;
 
ALTER TABLE CSM_PROTECTION_ELEMENT ADD CONSTRAINT UQ_PE_OBJ_ATT_VAL_APP_ID UNIQUE (OBJECT_ID, ATTRIBUTE, ATTRIBUTE_VALUE, APPLICATION_ID);

COMMIT;