CREATE SEQUENCE ACTIVITY_RELATIONSHIP_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE ACTIVITY_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE ADVERSE_EVENT_THERAPY_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE AGENT_OCCURRENCE_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE AGENT_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE ASSESSMENT_RELATIONSHIP_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE ASSESSMENT_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE CANCER_STAGE_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE CONCEPT_DESCRIPTOR_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE ELIGIBILITY_CHECKLIST_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE ELIGIBILITY_CHECKLST_CRITR_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE ELIGIBILITY_CRITERIA_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE FEMALE_REPRDCTVE_CHRCTRSTC_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE HEALTHCARE_SITE_INVESTIGTR_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE HEALTHCARE_SITE_PRTCPNT_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE HEALTHCARE_SIT_PRTCPNT_ROL_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE HISTOPATHOLOGY_GRADE_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE IDENTIFIER_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE LAB_VIEWER_STATUS_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE METASTASIS_SITE_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE NEOPLASM_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE OBSERVATION_ASSESSMENT_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE OBSERVATION_RELATIONSHIP_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE OBSERVATION_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE ORGANIZATION_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE PARTICIPANT_ELIGBLTY_ANSWR_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE PERSON_OCCUPATION_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE PERSON_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE PROTOCOL_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE PROTOCOL_PARTICPNT_ELGBLTY_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE PROTOCOL_STATUS_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE SPECIMEN_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE STUDY_AGENT_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE STUDY_INVESTIGATOR_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE STUDY_PARTICIPANT_ASSGNMNT_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE STUDY_SITE_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SEQUENCE STUDY_TIME_POINT_SEQ START WITH 1 INCREMENT BY 1
/
CREATE SYNONYM  HEALTHCARE_SITE_SEQ FOR ORGANIZATION_SEQ
/
CREATE SYNONYM  CENTRAL_LABORATORY_SEQ FOR ORGANIZATION_SEQ
/
CREATE SYNONYM  PERFORMING_LABORATORY_SEQ FOR ORGANIZATION_SEQ
/
CREATE SYNONYM  INVESTIGATOR_SEQ FOR PERSON_SEQ
/
CREATE SYNONYM  PARTICIPANT_SEQ FOR PERSON_SEQ
/
