DECLARE
   SYNNONYM_EXISTS NUMBER :=0;
BEGIN   

SELECT COUNT(*) INTO SYNNONYM_EXISTS 
FROM ALL_SYNONYMS
WHERE SYNONYM_NAME = 'HEALTHCARE_SITE_SEQ';

IF SYNNONYM_EXISTS > 0 THEN
   EXECUTE IMMEDIATE 'DROP SYNONYM  HEALTHCARE_SITE_SEQ';
END IF;

SELECT COUNT(*) INTO SYNNONYM_EXISTS 
FROM ALL_SYNONYMS
WHERE SYNONYM_NAME = 'CENTRAL_LABORATORY_SEQ';

IF SYNNONYM_EXISTS > 0 THEN
   EXECUTE IMMEDIATE 'DROP SYNONYM  CENTRAL_LABORATORY_SEQ';
END IF;

SELECT COUNT(*) INTO SYNNONYM_EXISTS 
FROM ALL_SYNONYMS
WHERE SYNONYM_NAME = 'PERFORMING_LABORATORY_SEQ';

IF SYNNONYM_EXISTS > 0 THEN
   EXECUTE IMMEDIATE 'DROP SYNONYM  PERFORMING_LABORATORY_SEQ';
END IF;

SELECT COUNT(*) INTO SYNNONYM_EXISTS 
FROM ALL_SYNONYMS
WHERE SYNONYM_NAME = 'INVESTIGATOR_SEQ';

IF SYNNONYM_EXISTS > 0 THEN
   EXECUTE IMMEDIATE 'DROP SYNONYM INVESTIGATOR_SEQ';
END IF;

SELECT COUNT(*) INTO SYNNONYM_EXISTS 
FROM ALL_SYNONYMS
WHERE SYNONYM_NAME = 'PARTICIPANT_SEQ';

IF SYNNONYM_EXISTS > 0 THEN
   EXECUTE IMMEDIATE 'DROP SYNONYM  PARTICIPANT_SEQ';
END IF;


END;
/