
DROP TABLE CSM_FILTER_CLAUSE CASCADE CONSTRAINTS;

DROP SEQUENCE CSM_FILTER_CLAUSE_FILTE_ID_SEQ;

CREATE TABLE CSM_FILTER_CLAUSE (
            FILTER_CLAUSE_ID NUMBER(38) NOT NULL,
            CLASS_NAME VARCHAR2(100) NOT NULL,
            FILTER_CHAIN VARCHAR2(2000) NOT NULL,
            TARGET_CLASS_NAME VARCHAR2(100) NOT NULL,
            TARGET_CLASS_ATTRIBUTE_NAME VARCHAR2(100) NOT NULL,
            TARGET_CLASS_ATTRIBUTE_TYPE VARCHAR2(100) NOT NULL,
            TARGET_CLASS_ALIAS VARCHAR2(100),
            TARGET_CLASS_ATTRIBUTE_ALIAS VARCHAR2(100),
            GENERATED_SQL VARCHAR2(4000) NOT NULL,
            APPLICATION_ID NUMBER(38) NOT NULL,
            UPDATE_DATE DATE NOT NULL
)
;

CREATE SEQUENCE CSM_FILTER_CLAUSE_FILTE_ID_SEQ
increment by 1
start with 1
NOMAXVALUE
minvalue 1
nocycle
nocache
noorder;

ALTER TABLE CSM_FILTER_CLAUSE ADD CONSTRAINT PK_FILTER_CLAUSE 
PRIMARY KEY (FILTER_CLAUSE_ID) 
;
 
ALTER TABLE CSM_PROTECTION_ELEMENT ADD ATTRIBUTE_VALUE VARCHAR2(100) ;
 
-- ALTER TABLE CSM_PROTECTION_ELEMENT DROP CONSTRAINT UQ_PE_OBJ_ATT_APP_ID;
 
ALTER TABLE CSM_PROTECTION_ELEMENT ADD CONSTRAINT UQ_PE_OBJ_ATT_VAL_APP_ID UNIQUE (OBJECT_ID, ATTRIBUTE, ATTRIBUTE_VALUE, APPLICATION_ID);

COMMIT;