package gov.nih.nci.caxchange.common;

import java.rmi.RemoteException;

/** 
 * This class is autogenerated, DO NOT EDIT.
 * 
 * This interface represents the API which is accessable on the grid service from the client. 
 * 
 * @created by Introduce Toolkit version 1.2
 * 
 */
public interface CaXchangeConsumerServiceI {

  public org.oasis.wsrf.properties.GetMultipleResourcePropertiesResponse getMultipleResourceProperties(org.oasis.wsrf.properties.GetMultipleResourceProperties_Element params) throws RemoteException ;

  public org.oasis.wsrf.properties.GetResourcePropertyResponse getResourceProperty(javax.xml.namespace.QName params) throws RemoteException ;

  public org.oasis.wsrf.properties.QueryResourcePropertiesResponse queryResourceProperties(org.oasis.wsrf.properties.QueryResourceProperties_Element params) throws RemoteException ;

  /**
   * Process a caXchange request message.
   *
   * @param caXchangeRequestMessage
   */
  public gov.nih.nci.caxchange.ConsumerResponseMessage process(gov.nih.nci.caxchange.Message caXchangeRequestMessage) throws RemoteException ;

  /**
   * Commiit changes to the target service
   *
   * @param caXchangeRequestMessage
   */
  public void commit(gov.nih.nci.caxchange.Message caXchangeRequestMessage) throws RemoteException ;

  /**
   * Rollback a transaction on the target service.
   *
   * @param caXchangeRequestMessage
   */
  public void rollback(gov.nih.nci.caxchange.Message caXchangeRequestMessage) throws RemoteException ;

}

